# Generated by Django 5.2.5 on 2026-01-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0011_alter_jigdetails_original_lot_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigdetails',
            name='delink_tray_info',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jigdetails',
            name='half_filled_tray_info',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jigdetails',
            name='partial_tray_info',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='draft_status',
            field=models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='jigloadtrayid',
            name='lot_id',
            field=models.CharField(blank=True, db_index=True, help_text='Lot ID', max_length=50, null=True),
        ),
    ]
