# Generated by Django 5.2.5 on 2026-01-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0012_jigdetails_delink_tray_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jigloadingmanualdraft',
            old_name='tray_info',
            new_name='delink_tray_info',
        ),
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='broken_hooks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='delink_tray_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='half_filled_tray_info',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='half_filled_tray_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='jig_capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='loaded_cases_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
