# Generated by Django 5.2.5 on 2026-01-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0013_rename_tray_info_jigloadingmanualdraft_delink_tray_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='jig_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
