# Generated by Django 5.2.5 on 2026-01-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0014_jigloadingmanualdraft_jig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='delink_tray_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
