# Generated by Django 5.2.5 on 2026-01-10 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0015_jigloadingmanualdraft_delink_tray_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JigCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(db_index=True, max_length=100)),
                ('lot_id', models.CharField(db_index=True, max_length=100)),
                ('draft_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jig_cases_remaining_count', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_lot_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('original_lot_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('jig_id', models.CharField(blank=True, max_length=100, null=True)),
                ('delink_tray_info', models.JSONField(blank=True, default=list, null=True)),
                ('delink_tray_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('delink_tray_count', models.IntegerField(blank=True, default=0, null=True)),
                ('half_filled_tray_info', models.JSONField(blank=True, default=list, null=True)),
                ('half_filled_tray_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('jig_capacity', models.IntegerField(blank=True, default=0, null=True)),
                ('broken_hooks', models.IntegerField(blank=True, default=0, null=True)),
                ('loaded_cases_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('draft_status', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('batch_id', 'lot_id', 'user')},
            },
        ),
    ]
