# Generated by Django 5.2.5 on 2026-01-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0016_jigcompleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jigcompleted',
            options={'verbose_name': 'Jig Completed', 'verbose_name_plural': 'Jig Completed'},
        ),
    ]
